import type { ApiErrorCode } from "../index.js";

const STATUS_BY_ERROR_CODE: Record<ApiErrorCode, number> = {
  INVALID_REQUEST: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  ROSTER_LIMIT_REACHED: 409,
  INVALID_STARTING_LOCATION: 422,
  INVALID_LOCATION: 422,
  CHARACTER_NOT_DRAFT: 409,
  CHARACTER_NOT_ELIGIBLE: 422,
  COMMITMENT_CONFLICT: 409,
  DOWNTIME_LIMIT_REACHED: 409,
  DOMAIN_VALIDATION_FAILED: 422,
  KB_WRITE_REJECTED: 409,
  KB_UNAVAILABLE: 500,
  INTERNAL_ERROR: 500,
};

export function mapDomainErrorToStatus(code: ApiErrorCode): number {
  return STATUS_BY_ERROR_CODE[code];
}
